version: "3"

services:
  git-clone:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_git_clone"
    command: git clone $PROJECT_GIT pece-distro
    volumes:
      - ./:/var/www/html

  update-project:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_update_project"
    environment:
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      COLUMNS: 80 # Set 80 columns for docker exec -it.
    volumes:
      - ./pece-distro:/var/www/html
